# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

env = GTK_THEME,Adwaita:dark

exec-once = waybar

exec-once = awww-daemon

exec-once = copyq
exec-once = synology-drive


# Fixing the weird display brightness problem
exec-once = bash -c "sleep 5 && ddcutil setvcp --display 3 10 90"


# Manually configuring RGB settings
exec-once = bash -c "openrgb --server & sleep 12 && ~/.config/hypr/scripts/openRGB_Final_Profile.sh" 



# ---- Launch and open windows ----
exec-once = flatpak run com.discordapp.Discord --enable-features=UseOzonePlatform --ozone-platform=wayland XDG_SESSION_TYPE=x11
exec-once = spotify

# Policykit thing
exec-once = /usr/bin/lxqt-policykit-agent


# QuickShell Overview
exec-once = qs -c overview
