# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto

# --- Monitor setup ---

# Left: Acer 1080p@120 Hz
monitor = HDMI-A-1,1920x1080@119.98,-1920x180,1

# Top-center: MSI G242 1080p@144 Hz
monitor = DP-1,1920x1080@143.85,320x-1080,1

# Center: MSI G273Q 1440p@165 Hz
monitor = DP-2,2560x1440@164.84,0x0,1


# --- Workspace -> Monitor mapping ---
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1

workspace = 7, monitor:DP-1, default:true
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1

workspace = 4, monitor:DP-2, default:true
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
