# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = dolphin

$menu = wofi --show drun

env = BROWSER,firefox
env = FILEMANAGER,dolphin


# ---- Binding some windows to workspaces upon launch ----
windowrule = match:class discord, workspace 1
windowrule = match:class spotify, workspace 7
windowrule = match:class steam,   workspace 8


# Adding tiling to hyperspeedcube
windowrule = tile on,  match:class hyperspeedcube

